// Linear CLI - Command-line interface for Linear issue tracking.
//
// Optimized for both human users and AI agents via MCP (Model Context Protocol).
// Uses ophis to automatically expose all Cobra commands as MCP tools.
//
// Usage:
//
//	export LINEAR_API_KEY=lin_api_xxx
//	linear issue list --team=Engineering --priority=1
//
// MCP Server Mode:
//
//	linear mcp serve
//
// The MCP server is automatically generated by ophis from the Cobra command tree.
package main

import (
	"os"

	"github.com/njayp/ophis"

	"github.com/chainguard-sandbox/go-linear/cmd/linear/commands"
)

func main() {
	rootCmd := commands.NewRootCommand()

	// Add ophis MCP integration
	// This single line exposes the entire CLI as an MCP server!
	// Ophis recursively walks the Cobra command tree and generates:
	// - JSON schemas from command flags
	// - MCP tool definitions
	// - Tool execution by spawning CLI subprocesses
	rootCmd.AddCommand(ophis.Command(nil))

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
