// Linear CLI - Command-line interface for Linear issue tracking.
//
// Optimized for both human users and AI agents via MCP (Model Context Protocol).
// Uses ophis to automatically expose all Cobra commands as MCP tools.
//
// Usage:
//
//	export LINEAR_API_KEY=lin_api_xxx
//	linear issue list --team=Engineering --priority=1
//
// MCP Server Mode:
//
//	linear mcp serve
//
// The MCP server is automatically generated by ophis from the Cobra command tree.
package main

import (
	"os"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/njayp/ophis"

	"github.com/chainguard-sandbox/go-linear/v2/cmd/linear/commands"
)

// mcpSelectors returns the ophis command selectors used to build the MCP tool
// set. The `graphql` escape hatch is a CLI-only command: it can run arbitrary
// mutations (behind --allow-mutation) and is deliberately NOT exposed as an MCP
// tool, so an agent cannot reach unrestricted GraphQL. Every other command is
// exposed with all of its flags. This is the single source of truth for the
// exclusion (see main_test.go).
func mcpSelectors() []ophis.Selector {
	return []ophis.Selector{{
		CmdSelector: ophis.ExcludeCmdsContaining("graphql"),
	}}
}

func main() {
	rootCmd := commands.NewRootCommand()

	rootCmd.AddCommand(ophis.Command(&ophis.Config{
		Transport: &fixFlagsTransport{inner: &mcp.StdioTransport{}},
		Selectors: mcpSelectors(),
	}))

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
