// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package graphql

import (
	"context"
	"time"

	"github.com/Yamashou/gqlgenc/clientv2"
)

type LinearGraphQLClient interface {
	Viewer(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Viewer, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) LinearGraphQLClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type Viewer_Viewer struct {
	Active      bool      "json:\"active\" graphql:\"active\""
	Admin       bool      "json:\"admin\" graphql:\"admin\""
	AvatarURL   *string   "json:\"avatarUrl,omitempty\" graphql:\"avatarUrl\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	Email       string    "json:\"email\" graphql:\"email\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
}

func (t *Viewer_Viewer) GetActive() bool {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.Active
}
func (t *Viewer_Viewer) GetAdmin() bool {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.Admin
}
func (t *Viewer_Viewer) GetAvatarURL() *string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.AvatarURL
}
func (t *Viewer_Viewer) GetCreatedAt() *time.Time {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return &t.CreatedAt
}
func (t *Viewer_Viewer) GetDisplayName() string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.DisplayName
}
func (t *Viewer_Viewer) GetEmail() string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.Email
}
func (t *Viewer_Viewer) GetID() string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.ID
}
func (t *Viewer_Viewer) GetName() string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.Name
}

type Viewer struct {
	Viewer Viewer_Viewer "json:\"viewer\" graphql:\"viewer\""
}

func (t *Viewer) GetViewer() *Viewer_Viewer {
	if t == nil {
		t = &Viewer{}
	}
	return &t.Viewer
}

const ViewerDocument = `query Viewer {
	viewer {
		id
		name
		email
		displayName
		createdAt
		admin
		active
		avatarUrl
	}
}
`

func (c *Client) Viewer(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Viewer, error) {
	vars := map[string]any{}

	var res Viewer
	if err := c.Client.Post(ctx, "Viewer", ViewerDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	ViewerDocument: "Viewer",
}
