// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package graphql

import (
	"context"
	"time"

	"github.com/Yamashou/gqlgenc/clientv2"
)

type LinearGraphQLClient interface {
	GetComment(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetComment, error)
	ListComments(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListComments, error)
	GetIssue(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetIssue, error)
	ListIssues(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListIssues, error)
	GetLabel(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetLabel, error)
	ListLabels(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListLabels, error)
	CreateIssue(ctx context.Context, input IssueCreateInput, interceptors ...clientv2.RequestInterceptor) (*CreateIssue, error)
	UpdateIssue(ctx context.Context, id string, input IssueUpdateInput, interceptors ...clientv2.RequestInterceptor) (*UpdateIssue, error)
	DeleteIssue(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*DeleteIssue, error)
	GetOrganization(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetOrganization, error)
	GetProject(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetProject, error)
	ListProjects(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListProjects, error)
	GetTeam(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetTeam, error)
	ListTeams(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListTeams, error)
	GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error)
	ListUsers(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListUsers, error)
	Viewer(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Viewer, error)
	GetWorkflowState(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetWorkflowState, error)
	ListWorkflowStates(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListWorkflowStates, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) LinearGraphQLClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetComment_Comment_User struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *GetComment_Comment_User) GetID() string {
	if t == nil {
		t = &GetComment_Comment_User{}
	}
	return t.ID
}
func (t *GetComment_Comment_User) GetName() string {
	if t == nil {
		t = &GetComment_Comment_User{}
	}
	return t.Name
}

type GetComment_Comment_Issue struct {
	ID    string "json:\"id\" graphql:\"id\""
	Title string "json:\"title\" graphql:\"title\""
}

func (t *GetComment_Comment_Issue) GetID() string {
	if t == nil {
		t = &GetComment_Comment_Issue{}
	}
	return t.ID
}
func (t *GetComment_Comment_Issue) GetTitle() string {
	if t == nil {
		t = &GetComment_Comment_Issue{}
	}
	return t.Title
}

type GetComment_Comment struct {
	Body      string                    "json:\"body\" graphql:\"body\""
	CreatedAt time.Time                 "json:\"createdAt\" graphql:\"createdAt\""
	ID        string                    "json:\"id\" graphql:\"id\""
	Issue     *GetComment_Comment_Issue "json:\"issue,omitempty\" graphql:\"issue\""
	UpdatedAt time.Time                 "json:\"updatedAt\" graphql:\"updatedAt\""
	URL       string                    "json:\"url\" graphql:\"url\""
	User      *GetComment_Comment_User  "json:\"user,omitempty\" graphql:\"user\""
}

func (t *GetComment_Comment) GetBody() string {
	if t == nil {
		t = &GetComment_Comment{}
	}
	return t.Body
}
func (t *GetComment_Comment) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetComment_Comment{}
	}
	return &t.CreatedAt
}
func (t *GetComment_Comment) GetID() string {
	if t == nil {
		t = &GetComment_Comment{}
	}
	return t.ID
}
func (t *GetComment_Comment) GetIssue() *GetComment_Comment_Issue {
	if t == nil {
		t = &GetComment_Comment{}
	}
	return t.Issue
}
func (t *GetComment_Comment) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetComment_Comment{}
	}
	return &t.UpdatedAt
}
func (t *GetComment_Comment) GetURL() string {
	if t == nil {
		t = &GetComment_Comment{}
	}
	return t.URL
}
func (t *GetComment_Comment) GetUser() *GetComment_Comment_User {
	if t == nil {
		t = &GetComment_Comment{}
	}
	return t.User
}

type ListComments_Comments_Nodes struct {
	Body      string    "json:\"body\" graphql:\"body\""
	CreatedAt time.Time "json:\"createdAt\" graphql:\"createdAt\""
	ID        string    "json:\"id\" graphql:\"id\""
	UpdatedAt time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
	URL       string    "json:\"url\" graphql:\"url\""
}

func (t *ListComments_Comments_Nodes) GetBody() string {
	if t == nil {
		t = &ListComments_Comments_Nodes{}
	}
	return t.Body
}
func (t *ListComments_Comments_Nodes) GetCreatedAt() *time.Time {
	if t == nil {
		t = &ListComments_Comments_Nodes{}
	}
	return &t.CreatedAt
}
func (t *ListComments_Comments_Nodes) GetID() string {
	if t == nil {
		t = &ListComments_Comments_Nodes{}
	}
	return t.ID
}
func (t *ListComments_Comments_Nodes) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &ListComments_Comments_Nodes{}
	}
	return &t.UpdatedAt
}
func (t *ListComments_Comments_Nodes) GetURL() string {
	if t == nil {
		t = &ListComments_Comments_Nodes{}
	}
	return t.URL
}

type ListComments_Comments_PageInfo struct {
	EndCursor   *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
}

func (t *ListComments_Comments_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &ListComments_Comments_PageInfo{}
	}
	return t.EndCursor
}
func (t *ListComments_Comments_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &ListComments_Comments_PageInfo{}
	}
	return t.HasNextPage
}

type ListComments_Comments struct {
	Nodes    []*ListComments_Comments_Nodes "json:\"nodes\" graphql:\"nodes\""
	PageInfo ListComments_Comments_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *ListComments_Comments) GetNodes() []*ListComments_Comments_Nodes {
	if t == nil {
		t = &ListComments_Comments{}
	}
	return t.Nodes
}
func (t *ListComments_Comments) GetPageInfo() *ListComments_Comments_PageInfo {
	if t == nil {
		t = &ListComments_Comments{}
	}
	return &t.PageInfo
}

type GetIssue_Issue_State struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
	Type string "json:\"type\" graphql:\"type\""
}

func (t *GetIssue_Issue_State) GetID() string {
	if t == nil {
		t = &GetIssue_Issue_State{}
	}
	return t.ID
}
func (t *GetIssue_Issue_State) GetName() string {
	if t == nil {
		t = &GetIssue_Issue_State{}
	}
	return t.Name
}
func (t *GetIssue_Issue_State) GetType() string {
	if t == nil {
		t = &GetIssue_Issue_State{}
	}
	return t.Type
}

type GetIssue_Issue_Team struct {
	ID   string "json:\"id\" graphql:\"id\""
	Key  string "json:\"key\" graphql:\"key\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *GetIssue_Issue_Team) GetID() string {
	if t == nil {
		t = &GetIssue_Issue_Team{}
	}
	return t.ID
}
func (t *GetIssue_Issue_Team) GetKey() string {
	if t == nil {
		t = &GetIssue_Issue_Team{}
	}
	return t.Key
}
func (t *GetIssue_Issue_Team) GetName() string {
	if t == nil {
		t = &GetIssue_Issue_Team{}
	}
	return t.Name
}

type GetIssue_Issue_Assignee struct {
	DisplayName string "json:\"displayName\" graphql:\"displayName\""
	ID          string "json:\"id\" graphql:\"id\""
	Name        string "json:\"name\" graphql:\"name\""
}

func (t *GetIssue_Issue_Assignee) GetDisplayName() string {
	if t == nil {
		t = &GetIssue_Issue_Assignee{}
	}
	return t.DisplayName
}
func (t *GetIssue_Issue_Assignee) GetID() string {
	if t == nil {
		t = &GetIssue_Issue_Assignee{}
	}
	return t.ID
}
func (t *GetIssue_Issue_Assignee) GetName() string {
	if t == nil {
		t = &GetIssue_Issue_Assignee{}
	}
	return t.Name
}

type GetIssue_Issue struct {
	Assignee    *GetIssue_Issue_Assignee "json:\"assignee,omitempty\" graphql:\"assignee\""
	CreatedAt   time.Time                "json:\"createdAt\" graphql:\"createdAt\""
	Description *string                  "json:\"description,omitempty\" graphql:\"description\""
	Estimate    *float64                 "json:\"estimate,omitempty\" graphql:\"estimate\""
	ID          string                   "json:\"id\" graphql:\"id\""
	Number      float64                  "json:\"number\" graphql:\"number\""
	Priority    float64                  "json:\"priority\" graphql:\"priority\""
	State       GetIssue_Issue_State     "json:\"state\" graphql:\"state\""
	Team        GetIssue_Issue_Team      "json:\"team\" graphql:\"team\""
	Title       string                   "json:\"title\" graphql:\"title\""
	UpdatedAt   time.Time                "json:\"updatedAt\" graphql:\"updatedAt\""
	URL         string                   "json:\"url\" graphql:\"url\""
}

func (t *GetIssue_Issue) GetAssignee() *GetIssue_Issue_Assignee {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return t.Assignee
}
func (t *GetIssue_Issue) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return &t.CreatedAt
}
func (t *GetIssue_Issue) GetDescription() *string {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return t.Description
}
func (t *GetIssue_Issue) GetEstimate() *float64 {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return t.Estimate
}
func (t *GetIssue_Issue) GetID() string {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return t.ID
}
func (t *GetIssue_Issue) GetNumber() float64 {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return t.Number
}
func (t *GetIssue_Issue) GetPriority() float64 {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return t.Priority
}
func (t *GetIssue_Issue) GetState() *GetIssue_Issue_State {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return &t.State
}
func (t *GetIssue_Issue) GetTeam() *GetIssue_Issue_Team {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return &t.Team
}
func (t *GetIssue_Issue) GetTitle() string {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return t.Title
}
func (t *GetIssue_Issue) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return &t.UpdatedAt
}
func (t *GetIssue_Issue) GetURL() string {
	if t == nil {
		t = &GetIssue_Issue{}
	}
	return t.URL
}

type ListIssues_Issues_Nodes_State struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *ListIssues_Issues_Nodes_State) GetID() string {
	if t == nil {
		t = &ListIssues_Issues_Nodes_State{}
	}
	return t.ID
}
func (t *ListIssues_Issues_Nodes_State) GetName() string {
	if t == nil {
		t = &ListIssues_Issues_Nodes_State{}
	}
	return t.Name
}

type ListIssues_Issues_Nodes_Team struct {
	ID   string "json:\"id\" graphql:\"id\""
	Key  string "json:\"key\" graphql:\"key\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *ListIssues_Issues_Nodes_Team) GetID() string {
	if t == nil {
		t = &ListIssues_Issues_Nodes_Team{}
	}
	return t.ID
}
func (t *ListIssues_Issues_Nodes_Team) GetKey() string {
	if t == nil {
		t = &ListIssues_Issues_Nodes_Team{}
	}
	return t.Key
}
func (t *ListIssues_Issues_Nodes_Team) GetName() string {
	if t == nil {
		t = &ListIssues_Issues_Nodes_Team{}
	}
	return t.Name
}

type ListIssues_Issues_Nodes struct {
	CreatedAt   time.Time                     "json:\"createdAt\" graphql:\"createdAt\""
	Description *string                       "json:\"description,omitempty\" graphql:\"description\""
	ID          string                        "json:\"id\" graphql:\"id\""
	Number      float64                       "json:\"number\" graphql:\"number\""
	Priority    float64                       "json:\"priority\" graphql:\"priority\""
	State       ListIssues_Issues_Nodes_State "json:\"state\" graphql:\"state\""
	Team        ListIssues_Issues_Nodes_Team  "json:\"team\" graphql:\"team\""
	Title       string                        "json:\"title\" graphql:\"title\""
	URL         string                        "json:\"url\" graphql:\"url\""
}

func (t *ListIssues_Issues_Nodes) GetCreatedAt() *time.Time {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return &t.CreatedAt
}
func (t *ListIssues_Issues_Nodes) GetDescription() *string {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return t.Description
}
func (t *ListIssues_Issues_Nodes) GetID() string {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return t.ID
}
func (t *ListIssues_Issues_Nodes) GetNumber() float64 {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return t.Number
}
func (t *ListIssues_Issues_Nodes) GetPriority() float64 {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return t.Priority
}
func (t *ListIssues_Issues_Nodes) GetState() *ListIssues_Issues_Nodes_State {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return &t.State
}
func (t *ListIssues_Issues_Nodes) GetTeam() *ListIssues_Issues_Nodes_Team {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return &t.Team
}
func (t *ListIssues_Issues_Nodes) GetTitle() string {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return t.Title
}
func (t *ListIssues_Issues_Nodes) GetURL() string {
	if t == nil {
		t = &ListIssues_Issues_Nodes{}
	}
	return t.URL
}

type ListIssues_Issues_PageInfo struct {
	EndCursor   *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
}

func (t *ListIssues_Issues_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &ListIssues_Issues_PageInfo{}
	}
	return t.EndCursor
}
func (t *ListIssues_Issues_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &ListIssues_Issues_PageInfo{}
	}
	return t.HasNextPage
}

type ListIssues_Issues struct {
	Nodes    []*ListIssues_Issues_Nodes "json:\"nodes\" graphql:\"nodes\""
	PageInfo ListIssues_Issues_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *ListIssues_Issues) GetNodes() []*ListIssues_Issues_Nodes {
	if t == nil {
		t = &ListIssues_Issues{}
	}
	return t.Nodes
}
func (t *ListIssues_Issues) GetPageInfo() *ListIssues_Issues_PageInfo {
	if t == nil {
		t = &ListIssues_Issues{}
	}
	return &t.PageInfo
}

type GetLabel_IssueLabel struct {
	Color       string    "json:\"color\" graphql:\"color\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
}

func (t *GetLabel_IssueLabel) GetColor() string {
	if t == nil {
		t = &GetLabel_IssueLabel{}
	}
	return t.Color
}
func (t *GetLabel_IssueLabel) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetLabel_IssueLabel{}
	}
	return &t.CreatedAt
}
func (t *GetLabel_IssueLabel) GetDescription() *string {
	if t == nil {
		t = &GetLabel_IssueLabel{}
	}
	return t.Description
}
func (t *GetLabel_IssueLabel) GetID() string {
	if t == nil {
		t = &GetLabel_IssueLabel{}
	}
	return t.ID
}
func (t *GetLabel_IssueLabel) GetName() string {
	if t == nil {
		t = &GetLabel_IssueLabel{}
	}
	return t.Name
}
func (t *GetLabel_IssueLabel) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetLabel_IssueLabel{}
	}
	return &t.UpdatedAt
}

type ListLabels_IssueLabels_Nodes struct {
	Color       string    "json:\"color\" graphql:\"color\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
}

func (t *ListLabels_IssueLabels_Nodes) GetColor() string {
	if t == nil {
		t = &ListLabels_IssueLabels_Nodes{}
	}
	return t.Color
}
func (t *ListLabels_IssueLabels_Nodes) GetCreatedAt() *time.Time {
	if t == nil {
		t = &ListLabels_IssueLabels_Nodes{}
	}
	return &t.CreatedAt
}
func (t *ListLabels_IssueLabels_Nodes) GetDescription() *string {
	if t == nil {
		t = &ListLabels_IssueLabels_Nodes{}
	}
	return t.Description
}
func (t *ListLabels_IssueLabels_Nodes) GetID() string {
	if t == nil {
		t = &ListLabels_IssueLabels_Nodes{}
	}
	return t.ID
}
func (t *ListLabels_IssueLabels_Nodes) GetName() string {
	if t == nil {
		t = &ListLabels_IssueLabels_Nodes{}
	}
	return t.Name
}

type ListLabels_IssueLabels_PageInfo struct {
	EndCursor   *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
}

func (t *ListLabels_IssueLabels_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &ListLabels_IssueLabels_PageInfo{}
	}
	return t.EndCursor
}
func (t *ListLabels_IssueLabels_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &ListLabels_IssueLabels_PageInfo{}
	}
	return t.HasNextPage
}

type ListLabels_IssueLabels struct {
	Nodes    []*ListLabels_IssueLabels_Nodes "json:\"nodes\" graphql:\"nodes\""
	PageInfo ListLabels_IssueLabels_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *ListLabels_IssueLabels) GetNodes() []*ListLabels_IssueLabels_Nodes {
	if t == nil {
		t = &ListLabels_IssueLabels{}
	}
	return t.Nodes
}
func (t *ListLabels_IssueLabels) GetPageInfo() *ListLabels_IssueLabels_PageInfo {
	if t == nil {
		t = &ListLabels_IssueLabels{}
	}
	return &t.PageInfo
}

type CreateIssue_IssueCreate_Issue_State struct {
	ID   string "json:\"id\" graphql:\"id\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *CreateIssue_IssueCreate_Issue_State) GetID() string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue_State{}
	}
	return t.ID
}
func (t *CreateIssue_IssueCreate_Issue_State) GetName() string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue_State{}
	}
	return t.Name
}

type CreateIssue_IssueCreate_Issue_Team struct {
	ID   string "json:\"id\" graphql:\"id\""
	Key  string "json:\"key\" graphql:\"key\""
	Name string "json:\"name\" graphql:\"name\""
}

func (t *CreateIssue_IssueCreate_Issue_Team) GetID() string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue_Team{}
	}
	return t.ID
}
func (t *CreateIssue_IssueCreate_Issue_Team) GetKey() string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue_Team{}
	}
	return t.Key
}
func (t *CreateIssue_IssueCreate_Issue_Team) GetName() string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue_Team{}
	}
	return t.Name
}

type CreateIssue_IssueCreate_Issue struct {
	CreatedAt   time.Time                           "json:\"createdAt\" graphql:\"createdAt\""
	Description *string                             "json:\"description,omitempty\" graphql:\"description\""
	ID          string                              "json:\"id\" graphql:\"id\""
	Number      float64                             "json:\"number\" graphql:\"number\""
	Priority    float64                             "json:\"priority\" graphql:\"priority\""
	State       CreateIssue_IssueCreate_Issue_State "json:\"state\" graphql:\"state\""
	Team        CreateIssue_IssueCreate_Issue_Team  "json:\"team\" graphql:\"team\""
	Title       string                              "json:\"title\" graphql:\"title\""
	URL         string                              "json:\"url\" graphql:\"url\""
}

func (t *CreateIssue_IssueCreate_Issue) GetCreatedAt() *time.Time {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return &t.CreatedAt
}
func (t *CreateIssue_IssueCreate_Issue) GetDescription() *string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return t.Description
}
func (t *CreateIssue_IssueCreate_Issue) GetID() string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return t.ID
}
func (t *CreateIssue_IssueCreate_Issue) GetNumber() float64 {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return t.Number
}
func (t *CreateIssue_IssueCreate_Issue) GetPriority() float64 {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return t.Priority
}
func (t *CreateIssue_IssueCreate_Issue) GetState() *CreateIssue_IssueCreate_Issue_State {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return &t.State
}
func (t *CreateIssue_IssueCreate_Issue) GetTeam() *CreateIssue_IssueCreate_Issue_Team {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return &t.Team
}
func (t *CreateIssue_IssueCreate_Issue) GetTitle() string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return t.Title
}
func (t *CreateIssue_IssueCreate_Issue) GetURL() string {
	if t == nil {
		t = &CreateIssue_IssueCreate_Issue{}
	}
	return t.URL
}

type CreateIssue_IssueCreate struct {
	Issue   *CreateIssue_IssueCreate_Issue "json:\"issue,omitempty\" graphql:\"issue\""
	Success bool                           "json:\"success\" graphql:\"success\""
}

func (t *CreateIssue_IssueCreate) GetIssue() *CreateIssue_IssueCreate_Issue {
	if t == nil {
		t = &CreateIssue_IssueCreate{}
	}
	return t.Issue
}
func (t *CreateIssue_IssueCreate) GetSuccess() bool {
	if t == nil {
		t = &CreateIssue_IssueCreate{}
	}
	return t.Success
}

type UpdateIssue_IssueUpdate_Issue struct {
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	ID          string    "json:\"id\" graphql:\"id\""
	Priority    float64   "json:\"priority\" graphql:\"priority\""
	Title       string    "json:\"title\" graphql:\"title\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
}

func (t *UpdateIssue_IssueUpdate_Issue) GetDescription() *string {
	if t == nil {
		t = &UpdateIssue_IssueUpdate_Issue{}
	}
	return t.Description
}
func (t *UpdateIssue_IssueUpdate_Issue) GetID() string {
	if t == nil {
		t = &UpdateIssue_IssueUpdate_Issue{}
	}
	return t.ID
}
func (t *UpdateIssue_IssueUpdate_Issue) GetPriority() float64 {
	if t == nil {
		t = &UpdateIssue_IssueUpdate_Issue{}
	}
	return t.Priority
}
func (t *UpdateIssue_IssueUpdate_Issue) GetTitle() string {
	if t == nil {
		t = &UpdateIssue_IssueUpdate_Issue{}
	}
	return t.Title
}
func (t *UpdateIssue_IssueUpdate_Issue) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &UpdateIssue_IssueUpdate_Issue{}
	}
	return &t.UpdatedAt
}

type UpdateIssue_IssueUpdate struct {
	Issue   *UpdateIssue_IssueUpdate_Issue "json:\"issue,omitempty\" graphql:\"issue\""
	Success bool                           "json:\"success\" graphql:\"success\""
}

func (t *UpdateIssue_IssueUpdate) GetIssue() *UpdateIssue_IssueUpdate_Issue {
	if t == nil {
		t = &UpdateIssue_IssueUpdate{}
	}
	return t.Issue
}
func (t *UpdateIssue_IssueUpdate) GetSuccess() bool {
	if t == nil {
		t = &UpdateIssue_IssueUpdate{}
	}
	return t.Success
}

type DeleteIssue_IssueDelete struct {
	Success bool "json:\"success\" graphql:\"success\""
}

func (t *DeleteIssue_IssueDelete) GetSuccess() bool {
	if t == nil {
		t = &DeleteIssue_IssueDelete{}
	}
	return t.Success
}

type GetOrganization_Organization struct {
	CreatedAt      time.Time "json:\"createdAt\" graphql:\"createdAt\""
	ID             string    "json:\"id\" graphql:\"id\""
	LogoURL        *string   "json:\"logoUrl,omitempty\" graphql:\"logoUrl\""
	Name           string    "json:\"name\" graphql:\"name\""
	RoadmapEnabled bool      "json:\"roadmapEnabled\" graphql:\"roadmapEnabled\""
	UpdatedAt      time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
	URLKey         string    "json:\"urlKey\" graphql:\"urlKey\""
}

func (t *GetOrganization_Organization) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetOrganization_Organization{}
	}
	return &t.CreatedAt
}
func (t *GetOrganization_Organization) GetID() string {
	if t == nil {
		t = &GetOrganization_Organization{}
	}
	return t.ID
}
func (t *GetOrganization_Organization) GetLogoURL() *string {
	if t == nil {
		t = &GetOrganization_Organization{}
	}
	return t.LogoURL
}
func (t *GetOrganization_Organization) GetName() string {
	if t == nil {
		t = &GetOrganization_Organization{}
	}
	return t.Name
}
func (t *GetOrganization_Organization) GetRoadmapEnabled() bool {
	if t == nil {
		t = &GetOrganization_Organization{}
	}
	return t.RoadmapEnabled
}
func (t *GetOrganization_Organization) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetOrganization_Organization{}
	}
	return &t.UpdatedAt
}
func (t *GetOrganization_Organization) GetURLKey() string {
	if t == nil {
		t = &GetOrganization_Organization{}
	}
	return t.URLKey
}

type GetProject_Project_Lead struct {
	Email string "json:\"email\" graphql:\"email\""
	ID    string "json:\"id\" graphql:\"id\""
	Name  string "json:\"name\" graphql:\"name\""
}

func (t *GetProject_Project_Lead) GetEmail() string {
	if t == nil {
		t = &GetProject_Project_Lead{}
	}
	return t.Email
}
func (t *GetProject_Project_Lead) GetID() string {
	if t == nil {
		t = &GetProject_Project_Lead{}
	}
	return t.ID
}
func (t *GetProject_Project_Lead) GetName() string {
	if t == nil {
		t = &GetProject_Project_Lead{}
	}
	return t.Name
}

type GetProject_Project struct {
	Color       string                   "json:\"color\" graphql:\"color\""
	CreatedAt   time.Time                "json:\"createdAt\" graphql:\"createdAt\""
	Description string                   "json:\"description\" graphql:\"description\""
	Icon        *string                  "json:\"icon,omitempty\" graphql:\"icon\""
	ID          string                   "json:\"id\" graphql:\"id\""
	Lead        *GetProject_Project_Lead "json:\"lead,omitempty\" graphql:\"lead\""
	Name        string                   "json:\"name\" graphql:\"name\""
	Progress    float64                  "json:\"progress\" graphql:\"progress\""
	StartedAt   *time.Time               "json:\"startedAt,omitempty\" graphql:\"startedAt\""
	State       string                   "json:\"state\" graphql:\"state\""
	TargetDate  *string                  "json:\"targetDate,omitempty\" graphql:\"targetDate\""
	UpdatedAt   time.Time                "json:\"updatedAt\" graphql:\"updatedAt\""
	URL         string                   "json:\"url\" graphql:\"url\""
}

func (t *GetProject_Project) GetColor() string {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.Color
}
func (t *GetProject_Project) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetProject_Project{}
	}
	return &t.CreatedAt
}
func (t *GetProject_Project) GetDescription() string {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.Description
}
func (t *GetProject_Project) GetIcon() *string {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.Icon
}
func (t *GetProject_Project) GetID() string {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.ID
}
func (t *GetProject_Project) GetLead() *GetProject_Project_Lead {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.Lead
}
func (t *GetProject_Project) GetName() string {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.Name
}
func (t *GetProject_Project) GetProgress() float64 {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.Progress
}
func (t *GetProject_Project) GetStartedAt() *time.Time {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.StartedAt
}
func (t *GetProject_Project) GetState() string {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.State
}
func (t *GetProject_Project) GetTargetDate() *string {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.TargetDate
}
func (t *GetProject_Project) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetProject_Project{}
	}
	return &t.UpdatedAt
}
func (t *GetProject_Project) GetURL() string {
	if t == nil {
		t = &GetProject_Project{}
	}
	return t.URL
}

type ListProjects_Projects_Nodes struct {
	Color       string    "json:\"color\" graphql:\"color\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	Description string    "json:\"description\" graphql:\"description\""
	Icon        *string   "json:\"icon,omitempty\" graphql:\"icon\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
	Progress    float64   "json:\"progress\" graphql:\"progress\""
	State       string    "json:\"state\" graphql:\"state\""
	TargetDate  *string   "json:\"targetDate,omitempty\" graphql:\"targetDate\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
	URL         string    "json:\"url\" graphql:\"url\""
}

func (t *ListProjects_Projects_Nodes) GetColor() string {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.Color
}
func (t *ListProjects_Projects_Nodes) GetCreatedAt() *time.Time {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return &t.CreatedAt
}
func (t *ListProjects_Projects_Nodes) GetDescription() string {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.Description
}
func (t *ListProjects_Projects_Nodes) GetIcon() *string {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.Icon
}
func (t *ListProjects_Projects_Nodes) GetID() string {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.ID
}
func (t *ListProjects_Projects_Nodes) GetName() string {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.Name
}
func (t *ListProjects_Projects_Nodes) GetProgress() float64 {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.Progress
}
func (t *ListProjects_Projects_Nodes) GetState() string {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.State
}
func (t *ListProjects_Projects_Nodes) GetTargetDate() *string {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.TargetDate
}
func (t *ListProjects_Projects_Nodes) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return &t.UpdatedAt
}
func (t *ListProjects_Projects_Nodes) GetURL() string {
	if t == nil {
		t = &ListProjects_Projects_Nodes{}
	}
	return t.URL
}

type ListProjects_Projects_PageInfo struct {
	EndCursor   *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
}

func (t *ListProjects_Projects_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &ListProjects_Projects_PageInfo{}
	}
	return t.EndCursor
}
func (t *ListProjects_Projects_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &ListProjects_Projects_PageInfo{}
	}
	return t.HasNextPage
}

type ListProjects_Projects struct {
	Nodes    []*ListProjects_Projects_Nodes "json:\"nodes\" graphql:\"nodes\""
	PageInfo ListProjects_Projects_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *ListProjects_Projects) GetNodes() []*ListProjects_Projects_Nodes {
	if t == nil {
		t = &ListProjects_Projects{}
	}
	return t.Nodes
}
func (t *ListProjects_Projects) GetPageInfo() *ListProjects_Projects_PageInfo {
	if t == nil {
		t = &ListProjects_Projects{}
	}
	return &t.PageInfo
}

type GetTeam_Team struct {
	Color       *string   "json:\"color,omitempty\" graphql:\"color\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	Icon        *string   "json:\"icon,omitempty\" graphql:\"icon\""
	ID          string    "json:\"id\" graphql:\"id\""
	Key         string    "json:\"key\" graphql:\"key\""
	Name        string    "json:\"name\" graphql:\"name\""
	Private     bool      "json:\"private\" graphql:\"private\""
	Timezone    string    "json:\"timezone\" graphql:\"timezone\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
}

func (t *GetTeam_Team) GetColor() *string {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return t.Color
}
func (t *GetTeam_Team) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return &t.CreatedAt
}
func (t *GetTeam_Team) GetDescription() *string {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return t.Description
}
func (t *GetTeam_Team) GetIcon() *string {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return t.Icon
}
func (t *GetTeam_Team) GetID() string {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return t.ID
}
func (t *GetTeam_Team) GetKey() string {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return t.Key
}
func (t *GetTeam_Team) GetName() string {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return t.Name
}
func (t *GetTeam_Team) GetPrivate() bool {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return t.Private
}
func (t *GetTeam_Team) GetTimezone() string {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return t.Timezone
}
func (t *GetTeam_Team) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetTeam_Team{}
	}
	return &t.UpdatedAt
}

type ListTeams_Teams_Nodes struct {
	Color       *string   "json:\"color,omitempty\" graphql:\"color\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	Icon        *string   "json:\"icon,omitempty\" graphql:\"icon\""
	ID          string    "json:\"id\" graphql:\"id\""
	Key         string    "json:\"key\" graphql:\"key\""
	Name        string    "json:\"name\" graphql:\"name\""
	Private     bool      "json:\"private\" graphql:\"private\""
}

func (t *ListTeams_Teams_Nodes) GetColor() *string {
	if t == nil {
		t = &ListTeams_Teams_Nodes{}
	}
	return t.Color
}
func (t *ListTeams_Teams_Nodes) GetCreatedAt() *time.Time {
	if t == nil {
		t = &ListTeams_Teams_Nodes{}
	}
	return &t.CreatedAt
}
func (t *ListTeams_Teams_Nodes) GetDescription() *string {
	if t == nil {
		t = &ListTeams_Teams_Nodes{}
	}
	return t.Description
}
func (t *ListTeams_Teams_Nodes) GetIcon() *string {
	if t == nil {
		t = &ListTeams_Teams_Nodes{}
	}
	return t.Icon
}
func (t *ListTeams_Teams_Nodes) GetID() string {
	if t == nil {
		t = &ListTeams_Teams_Nodes{}
	}
	return t.ID
}
func (t *ListTeams_Teams_Nodes) GetKey() string {
	if t == nil {
		t = &ListTeams_Teams_Nodes{}
	}
	return t.Key
}
func (t *ListTeams_Teams_Nodes) GetName() string {
	if t == nil {
		t = &ListTeams_Teams_Nodes{}
	}
	return t.Name
}
func (t *ListTeams_Teams_Nodes) GetPrivate() bool {
	if t == nil {
		t = &ListTeams_Teams_Nodes{}
	}
	return t.Private
}

type ListTeams_Teams_PageInfo struct {
	EndCursor   *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
}

func (t *ListTeams_Teams_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &ListTeams_Teams_PageInfo{}
	}
	return t.EndCursor
}
func (t *ListTeams_Teams_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &ListTeams_Teams_PageInfo{}
	}
	return t.HasNextPage
}

type ListTeams_Teams struct {
	Nodes    []*ListTeams_Teams_Nodes "json:\"nodes\" graphql:\"nodes\""
	PageInfo ListTeams_Teams_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *ListTeams_Teams) GetNodes() []*ListTeams_Teams_Nodes {
	if t == nil {
		t = &ListTeams_Teams{}
	}
	return t.Nodes
}
func (t *ListTeams_Teams) GetPageInfo() *ListTeams_Teams_PageInfo {
	if t == nil {
		t = &ListTeams_Teams{}
	}
	return &t.PageInfo
}

type GetUser_User struct {
	Active      bool      "json:\"active\" graphql:\"active\""
	Admin       bool      "json:\"admin\" graphql:\"admin\""
	AvatarURL   *string   "json:\"avatarUrl,omitempty\" graphql:\"avatarUrl\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	Email       string    "json:\"email\" graphql:\"email\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
}

func (t *GetUser_User) GetActive() bool {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Active
}
func (t *GetUser_User) GetAdmin() bool {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Admin
}
func (t *GetUser_User) GetAvatarURL() *string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.AvatarURL
}
func (t *GetUser_User) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetUser_User{}
	}
	return &t.CreatedAt
}
func (t *GetUser_User) GetDisplayName() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.DisplayName
}
func (t *GetUser_User) GetEmail() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Email
}
func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetName() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Name
}
func (t *GetUser_User) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetUser_User{}
	}
	return &t.UpdatedAt
}

type ListUsers_Users_Nodes struct {
	Active      bool      "json:\"active\" graphql:\"active\""
	Admin       bool      "json:\"admin\" graphql:\"admin\""
	AvatarURL   *string   "json:\"avatarUrl,omitempty\" graphql:\"avatarUrl\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	Email       string    "json:\"email\" graphql:\"email\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
}

func (t *ListUsers_Users_Nodes) GetActive() bool {
	if t == nil {
		t = &ListUsers_Users_Nodes{}
	}
	return t.Active
}
func (t *ListUsers_Users_Nodes) GetAdmin() bool {
	if t == nil {
		t = &ListUsers_Users_Nodes{}
	}
	return t.Admin
}
func (t *ListUsers_Users_Nodes) GetAvatarURL() *string {
	if t == nil {
		t = &ListUsers_Users_Nodes{}
	}
	return t.AvatarURL
}
func (t *ListUsers_Users_Nodes) GetCreatedAt() *time.Time {
	if t == nil {
		t = &ListUsers_Users_Nodes{}
	}
	return &t.CreatedAt
}
func (t *ListUsers_Users_Nodes) GetDisplayName() string {
	if t == nil {
		t = &ListUsers_Users_Nodes{}
	}
	return t.DisplayName
}
func (t *ListUsers_Users_Nodes) GetEmail() string {
	if t == nil {
		t = &ListUsers_Users_Nodes{}
	}
	return t.Email
}
func (t *ListUsers_Users_Nodes) GetID() string {
	if t == nil {
		t = &ListUsers_Users_Nodes{}
	}
	return t.ID
}
func (t *ListUsers_Users_Nodes) GetName() string {
	if t == nil {
		t = &ListUsers_Users_Nodes{}
	}
	return t.Name
}

type ListUsers_Users_PageInfo struct {
	EndCursor   *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
}

func (t *ListUsers_Users_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &ListUsers_Users_PageInfo{}
	}
	return t.EndCursor
}
func (t *ListUsers_Users_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &ListUsers_Users_PageInfo{}
	}
	return t.HasNextPage
}

type ListUsers_Users struct {
	Nodes    []*ListUsers_Users_Nodes "json:\"nodes\" graphql:\"nodes\""
	PageInfo ListUsers_Users_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *ListUsers_Users) GetNodes() []*ListUsers_Users_Nodes {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return t.Nodes
}
func (t *ListUsers_Users) GetPageInfo() *ListUsers_Users_PageInfo {
	if t == nil {
		t = &ListUsers_Users{}
	}
	return &t.PageInfo
}

type Viewer_Viewer struct {
	Active      bool      "json:\"active\" graphql:\"active\""
	Admin       bool      "json:\"admin\" graphql:\"admin\""
	AvatarURL   *string   "json:\"avatarUrl,omitempty\" graphql:\"avatarUrl\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	Email       string    "json:\"email\" graphql:\"email\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
}

func (t *Viewer_Viewer) GetActive() bool {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.Active
}
func (t *Viewer_Viewer) GetAdmin() bool {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.Admin
}
func (t *Viewer_Viewer) GetAvatarURL() *string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.AvatarURL
}
func (t *Viewer_Viewer) GetCreatedAt() *time.Time {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return &t.CreatedAt
}
func (t *Viewer_Viewer) GetDisplayName() string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.DisplayName
}
func (t *Viewer_Viewer) GetEmail() string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.Email
}
func (t *Viewer_Viewer) GetID() string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.ID
}
func (t *Viewer_Viewer) GetName() string {
	if t == nil {
		t = &Viewer_Viewer{}
	}
	return t.Name
}

type GetWorkflowState_WorkflowState struct {
	Color       string    "json:\"color\" graphql:\"color\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
	Position    float64   "json:\"position\" graphql:\"position\""
	Type        string    "json:\"type\" graphql:\"type\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
}

func (t *GetWorkflowState_WorkflowState) GetColor() string {
	if t == nil {
		t = &GetWorkflowState_WorkflowState{}
	}
	return t.Color
}
func (t *GetWorkflowState_WorkflowState) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetWorkflowState_WorkflowState{}
	}
	return &t.CreatedAt
}
func (t *GetWorkflowState_WorkflowState) GetDescription() *string {
	if t == nil {
		t = &GetWorkflowState_WorkflowState{}
	}
	return t.Description
}
func (t *GetWorkflowState_WorkflowState) GetID() string {
	if t == nil {
		t = &GetWorkflowState_WorkflowState{}
	}
	return t.ID
}
func (t *GetWorkflowState_WorkflowState) GetName() string {
	if t == nil {
		t = &GetWorkflowState_WorkflowState{}
	}
	return t.Name
}
func (t *GetWorkflowState_WorkflowState) GetPosition() float64 {
	if t == nil {
		t = &GetWorkflowState_WorkflowState{}
	}
	return t.Position
}
func (t *GetWorkflowState_WorkflowState) GetType() string {
	if t == nil {
		t = &GetWorkflowState_WorkflowState{}
	}
	return t.Type
}
func (t *GetWorkflowState_WorkflowState) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetWorkflowState_WorkflowState{}
	}
	return &t.UpdatedAt
}

type ListWorkflowStates_WorkflowStates_Nodes struct {
	Color       string    "json:\"color\" graphql:\"color\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
	Position    float64   "json:\"position\" graphql:\"position\""
	Type        string    "json:\"type\" graphql:\"type\""
}

func (t *ListWorkflowStates_WorkflowStates_Nodes) GetColor() string {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_Nodes{}
	}
	return t.Color
}
func (t *ListWorkflowStates_WorkflowStates_Nodes) GetCreatedAt() *time.Time {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_Nodes{}
	}
	return &t.CreatedAt
}
func (t *ListWorkflowStates_WorkflowStates_Nodes) GetDescription() *string {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_Nodes{}
	}
	return t.Description
}
func (t *ListWorkflowStates_WorkflowStates_Nodes) GetID() string {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_Nodes{}
	}
	return t.ID
}
func (t *ListWorkflowStates_WorkflowStates_Nodes) GetName() string {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_Nodes{}
	}
	return t.Name
}
func (t *ListWorkflowStates_WorkflowStates_Nodes) GetPosition() float64 {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_Nodes{}
	}
	return t.Position
}
func (t *ListWorkflowStates_WorkflowStates_Nodes) GetType() string {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_Nodes{}
	}
	return t.Type
}

type ListWorkflowStates_WorkflowStates_PageInfo struct {
	EndCursor   *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
}

func (t *ListWorkflowStates_WorkflowStates_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_PageInfo{}
	}
	return t.EndCursor
}
func (t *ListWorkflowStates_WorkflowStates_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates_PageInfo{}
	}
	return t.HasNextPage
}

type ListWorkflowStates_WorkflowStates struct {
	Nodes    []*ListWorkflowStates_WorkflowStates_Nodes "json:\"nodes\" graphql:\"nodes\""
	PageInfo ListWorkflowStates_WorkflowStates_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *ListWorkflowStates_WorkflowStates) GetNodes() []*ListWorkflowStates_WorkflowStates_Nodes {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates{}
	}
	return t.Nodes
}
func (t *ListWorkflowStates_WorkflowStates) GetPageInfo() *ListWorkflowStates_WorkflowStates_PageInfo {
	if t == nil {
		t = &ListWorkflowStates_WorkflowStates{}
	}
	return &t.PageInfo
}

type GetComment struct {
	Comment GetComment_Comment "json:\"comment\" graphql:\"comment\""
}

func (t *GetComment) GetComment() *GetComment_Comment {
	if t == nil {
		t = &GetComment{}
	}
	return &t.Comment
}

type ListComments struct {
	Comments ListComments_Comments "json:\"comments\" graphql:\"comments\""
}

func (t *ListComments) GetComments() *ListComments_Comments {
	if t == nil {
		t = &ListComments{}
	}
	return &t.Comments
}

type GetIssue struct {
	Issue GetIssue_Issue "json:\"issue\" graphql:\"issue\""
}

func (t *GetIssue) GetIssue() *GetIssue_Issue {
	if t == nil {
		t = &GetIssue{}
	}
	return &t.Issue
}

type ListIssues struct {
	Issues ListIssues_Issues "json:\"issues\" graphql:\"issues\""
}

func (t *ListIssues) GetIssues() *ListIssues_Issues {
	if t == nil {
		t = &ListIssues{}
	}
	return &t.Issues
}

type GetLabel struct {
	IssueLabel GetLabel_IssueLabel "json:\"issueLabel\" graphql:\"issueLabel\""
}

func (t *GetLabel) GetIssueLabel() *GetLabel_IssueLabel {
	if t == nil {
		t = &GetLabel{}
	}
	return &t.IssueLabel
}

type ListLabels struct {
	IssueLabels ListLabels_IssueLabels "json:\"issueLabels\" graphql:\"issueLabels\""
}

func (t *ListLabels) GetIssueLabels() *ListLabels_IssueLabels {
	if t == nil {
		t = &ListLabels{}
	}
	return &t.IssueLabels
}

type CreateIssue struct {
	IssueCreate CreateIssue_IssueCreate "json:\"issueCreate\" graphql:\"issueCreate\""
}

func (t *CreateIssue) GetIssueCreate() *CreateIssue_IssueCreate {
	if t == nil {
		t = &CreateIssue{}
	}
	return &t.IssueCreate
}

type UpdateIssue struct {
	IssueUpdate UpdateIssue_IssueUpdate "json:\"issueUpdate\" graphql:\"issueUpdate\""
}

func (t *UpdateIssue) GetIssueUpdate() *UpdateIssue_IssueUpdate {
	if t == nil {
		t = &UpdateIssue{}
	}
	return &t.IssueUpdate
}

type DeleteIssue struct {
	IssueDelete DeleteIssue_IssueDelete "json:\"issueDelete\" graphql:\"issueDelete\""
}

func (t *DeleteIssue) GetIssueDelete() *DeleteIssue_IssueDelete {
	if t == nil {
		t = &DeleteIssue{}
	}
	return &t.IssueDelete
}

type GetOrganization struct {
	Organization GetOrganization_Organization "json:\"organization\" graphql:\"organization\""
}

func (t *GetOrganization) GetOrganization() *GetOrganization_Organization {
	if t == nil {
		t = &GetOrganization{}
	}
	return &t.Organization
}

type GetProject struct {
	Project GetProject_Project "json:\"project\" graphql:\"project\""
}

func (t *GetProject) GetProject() *GetProject_Project {
	if t == nil {
		t = &GetProject{}
	}
	return &t.Project
}

type ListProjects struct {
	Projects ListProjects_Projects "json:\"projects\" graphql:\"projects\""
}

func (t *ListProjects) GetProjects() *ListProjects_Projects {
	if t == nil {
		t = &ListProjects{}
	}
	return &t.Projects
}

type GetTeam struct {
	Team GetTeam_Team "json:\"team\" graphql:\"team\""
}

func (t *GetTeam) GetTeam() *GetTeam_Team {
	if t == nil {
		t = &GetTeam{}
	}
	return &t.Team
}

type ListTeams struct {
	Teams ListTeams_Teams "json:\"teams\" graphql:\"teams\""
}

func (t *ListTeams) GetTeams() *ListTeams_Teams {
	if t == nil {
		t = &ListTeams{}
	}
	return &t.Teams
}

type GetUser struct {
	User GetUser_User "json:\"user\" graphql:\"user\""
}

func (t *GetUser) GetUser() *GetUser_User {
	if t == nil {
		t = &GetUser{}
	}
	return &t.User
}

type ListUsers struct {
	Users ListUsers_Users "json:\"users\" graphql:\"users\""
}

func (t *ListUsers) GetUsers() *ListUsers_Users {
	if t == nil {
		t = &ListUsers{}
	}
	return &t.Users
}

type Viewer struct {
	Viewer Viewer_Viewer "json:\"viewer\" graphql:\"viewer\""
}

func (t *Viewer) GetViewer() *Viewer_Viewer {
	if t == nil {
		t = &Viewer{}
	}
	return &t.Viewer
}

type GetWorkflowState struct {
	WorkflowState GetWorkflowState_WorkflowState "json:\"workflowState\" graphql:\"workflowState\""
}

func (t *GetWorkflowState) GetWorkflowState() *GetWorkflowState_WorkflowState {
	if t == nil {
		t = &GetWorkflowState{}
	}
	return &t.WorkflowState
}

type ListWorkflowStates struct {
	WorkflowStates ListWorkflowStates_WorkflowStates "json:\"workflowStates\" graphql:\"workflowStates\""
}

func (t *ListWorkflowStates) GetWorkflowStates() *ListWorkflowStates_WorkflowStates {
	if t == nil {
		t = &ListWorkflowStates{}
	}
	return &t.WorkflowStates
}

const GetCommentDocument = `query GetComment ($id: String!) {
	comment(id: $id) {
		id
		body
		createdAt
		updatedAt
		url
		user {
			id
			name
		}
		issue {
			id
			title
		}
	}
}
`

func (c *Client) GetComment(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetComment, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetComment
	if err := c.Client.Post(ctx, "GetComment", GetCommentDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListCommentsDocument = `query ListComments ($first: Int, $after: String) {
	comments(first: $first, after: $after) {
		nodes {
			id
			body
			createdAt
			updatedAt
			url
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func (c *Client) ListComments(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListComments, error) {
	vars := map[string]any{
		"first": first,
		"after": after,
	}

	var res ListComments
	if err := c.Client.Post(ctx, "ListComments", ListCommentsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetIssueDocument = `query GetIssue ($id: String!) {
	issue(id: $id) {
		id
		title
		description
		priority
		estimate
		createdAt
		updatedAt
		number
		url
		state {
			id
			name
			type
		}
		team {
			id
			name
			key
		}
		assignee {
			id
			name
			displayName
		}
	}
}
`

func (c *Client) GetIssue(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetIssue, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetIssue
	if err := c.Client.Post(ctx, "GetIssue", GetIssueDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListIssuesDocument = `query ListIssues ($first: Int, $after: String) {
	issues(first: $first, after: $after) {
		nodes {
			id
			title
			description
			priority
			createdAt
			number
			url
			state {
				id
				name
			}
			team {
				id
				name
				key
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func (c *Client) ListIssues(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListIssues, error) {
	vars := map[string]any{
		"first": first,
		"after": after,
	}

	var res ListIssues
	if err := c.Client.Post(ctx, "ListIssues", ListIssuesDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetLabelDocument = `query GetLabel ($id: String!) {
	issueLabel(id: $id) {
		id
		name
		description
		color
		createdAt
		updatedAt
	}
}
`

func (c *Client) GetLabel(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetLabel, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetLabel
	if err := c.Client.Post(ctx, "GetLabel", GetLabelDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListLabelsDocument = `query ListLabels ($first: Int, $after: String) {
	issueLabels(first: $first, after: $after) {
		nodes {
			id
			name
			description
			color
			createdAt
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func (c *Client) ListLabels(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListLabels, error) {
	vars := map[string]any{
		"first": first,
		"after": after,
	}

	var res ListLabels
	if err := c.Client.Post(ctx, "ListLabels", ListLabelsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const CreateIssueDocument = `mutation CreateIssue ($input: IssueCreateInput!) {
	issueCreate(input: $input) {
		success
		issue {
			id
			title
			description
			priority
			createdAt
			number
			url
			state {
				id
				name
			}
			team {
				id
				name
				key
			}
		}
	}
}
`

func (c *Client) CreateIssue(ctx context.Context, input IssueCreateInput, interceptors ...clientv2.RequestInterceptor) (*CreateIssue, error) {
	vars := map[string]any{
		"input": input,
	}

	var res CreateIssue
	if err := c.Client.Post(ctx, "CreateIssue", CreateIssueDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const UpdateIssueDocument = `mutation UpdateIssue ($id: String!, $input: IssueUpdateInput!) {
	issueUpdate(id: $id, input: $input) {
		success
		issue {
			id
			title
			description
			priority
			updatedAt
		}
	}
}
`

func (c *Client) UpdateIssue(ctx context.Context, id string, input IssueUpdateInput, interceptors ...clientv2.RequestInterceptor) (*UpdateIssue, error) {
	vars := map[string]any{
		"id":    id,
		"input": input,
	}

	var res UpdateIssue
	if err := c.Client.Post(ctx, "UpdateIssue", UpdateIssueDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const DeleteIssueDocument = `mutation DeleteIssue ($id: String!) {
	issueDelete(id: $id) {
		success
	}
}
`

func (c *Client) DeleteIssue(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*DeleteIssue, error) {
	vars := map[string]any{
		"id": id,
	}

	var res DeleteIssue
	if err := c.Client.Post(ctx, "DeleteIssue", DeleteIssueDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetOrganizationDocument = `query GetOrganization {
	organization {
		id
		name
		urlKey
		logoUrl
		createdAt
		updatedAt
		roadmapEnabled
	}
}
`

func (c *Client) GetOrganization(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetOrganization, error) {
	vars := map[string]any{}

	var res GetOrganization
	if err := c.Client.Post(ctx, "GetOrganization", GetOrganizationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetProjectDocument = `query GetProject ($id: String!) {
	project(id: $id) {
		id
		name
		description
		state
		createdAt
		updatedAt
		startedAt
		targetDate
		progress
		url
		icon
		color
		lead {
			id
			name
			email
		}
	}
}
`

func (c *Client) GetProject(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetProject, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetProject
	if err := c.Client.Post(ctx, "GetProject", GetProjectDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListProjectsDocument = `query ListProjects ($first: Int, $after: String) {
	projects(first: $first, after: $after) {
		nodes {
			id
			name
			description
			state
			createdAt
			updatedAt
			targetDate
			progress
			url
			icon
			color
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func (c *Client) ListProjects(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListProjects, error) {
	vars := map[string]any{
		"first": first,
		"after": after,
	}

	var res ListProjects
	if err := c.Client.Post(ctx, "ListProjects", ListProjectsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetTeamDocument = `query GetTeam ($id: String!) {
	team(id: $id) {
		id
		name
		key
		description
		createdAt
		updatedAt
		private
		timezone
		icon
		color
	}
}
`

func (c *Client) GetTeam(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetTeam, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetTeam
	if err := c.Client.Post(ctx, "GetTeam", GetTeamDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListTeamsDocument = `query ListTeams ($first: Int, $after: String) {
	teams(first: $first, after: $after) {
		nodes {
			id
			name
			key
			description
			createdAt
			private
			icon
			color
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func (c *Client) ListTeams(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListTeams, error) {
	vars := map[string]any{
		"first": first,
		"after": after,
	}

	var res ListTeams
	if err := c.Client.Post(ctx, "ListTeams", ListTeamsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetUserDocument = `query GetUser ($id: String!) {
	user(id: $id) {
		id
		name
		email
		displayName
		createdAt
		updatedAt
		admin
		active
		avatarUrl
	}
}
`

func (c *Client) GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetUser
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListUsersDocument = `query ListUsers ($first: Int, $after: String) {
	users(first: $first, after: $after) {
		nodes {
			id
			name
			email
			displayName
			createdAt
			admin
			active
			avatarUrl
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func (c *Client) ListUsers(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListUsers, error) {
	vars := map[string]any{
		"first": first,
		"after": after,
	}

	var res ListUsers
	if err := c.Client.Post(ctx, "ListUsers", ListUsersDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ViewerDocument = `query Viewer {
	viewer {
		id
		name
		email
		displayName
		createdAt
		admin
		active
		avatarUrl
	}
}
`

func (c *Client) Viewer(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Viewer, error) {
	vars := map[string]any{}

	var res Viewer
	if err := c.Client.Post(ctx, "Viewer", ViewerDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetWorkflowStateDocument = `query GetWorkflowState ($id: String!) {
	workflowState(id: $id) {
		id
		name
		description
		type
		color
		position
		createdAt
		updatedAt
	}
}
`

func (c *Client) GetWorkflowState(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetWorkflowState, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetWorkflowState
	if err := c.Client.Post(ctx, "GetWorkflowState", GetWorkflowStateDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const ListWorkflowStatesDocument = `query ListWorkflowStates ($first: Int, $after: String) {
	workflowStates(first: $first, after: $after) {
		nodes {
			id
			name
			description
			type
			color
			position
			createdAt
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func (c *Client) ListWorkflowStates(ctx context.Context, first *int64, after *string, interceptors ...clientv2.RequestInterceptor) (*ListWorkflowStates, error) {
	vars := map[string]any{
		"first": first,
		"after": after,
	}

	var res ListWorkflowStates
	if err := c.Client.Post(ctx, "ListWorkflowStates", ListWorkflowStatesDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetCommentDocument:         "GetComment",
	ListCommentsDocument:       "ListComments",
	GetIssueDocument:           "GetIssue",
	ListIssuesDocument:         "ListIssues",
	GetLabelDocument:           "GetLabel",
	ListLabelsDocument:         "ListLabels",
	CreateIssueDocument:        "CreateIssue",
	UpdateIssueDocument:        "UpdateIssue",
	DeleteIssueDocument:        "DeleteIssue",
	GetOrganizationDocument:    "GetOrganization",
	GetProjectDocument:         "GetProject",
	ListProjectsDocument:       "ListProjects",
	GetTeamDocument:            "GetTeam",
	ListTeamsDocument:          "ListTeams",
	GetUserDocument:            "GetUser",
	ListUsersDocument:          "ListUsers",
	ViewerDocument:             "Viewer",
	GetWorkflowStateDocument:   "GetWorkflowState",
	ListWorkflowStatesDocument: "ListWorkflowStates",
}
